name: Test Simple

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Good checkout with SHA
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Bad checkout with tag
        uses: actions/checkout@v4

      - name: Another bad action
        uses: actions/upload-artifact@main
